name: generos_nomes
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
