name: generos_nome_ordenacao
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  csv: ^6.0.0
  crypto: ^3.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
